version: 0.0
os: linux
files:
  - source: convertTemp/convertTemp/target/TemperatureConvert.jar
    destination: /home/ec2-user/application/

hooks:
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ec2-user
