version: 0.0
Resources:
  - myLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: TempConvertFunction
        Alias: live
	CurrentVersion: "1"
        TargetVersion: "2"
Hooks:
  - BeforeAllowTraffic:
      - location: scripts/validate.sh
        timeout: 300
        runas: root
  - AfterAllowTraffic:
      - location: scripts/post_deploy.sh
        timeout: 300
        runas: root
