apiVersion: apps/v1
kind: Deployment
metadata:
  name: configdeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configapp
  template:
    metadata:
      labels:
        app: configapp
    spec:
      containers:
      - name: configcontainer
        image: gcr.io/omega-booster-422417-n5/config-server:1.0
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: config-service
spec:
  type: LoadBalancer
  selector:
    app: configapp
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
