apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysql
  replicas: 2  # Adjust number of replicas as needed
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "atmadeep"
        ports:
        - containerPort: 3306
          name: mysql
        resources:
          requests:
            memory: "512Mi"  # Adjust memory request as needed
            cpu: "0.5"        # Adjust CPU request as needed
          limits:
            memory: "1Gi"     # Adjust memory limit as needed
            cpu: "0.5"        # Adjust CPU limit as needed
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-persistent-storage
  volumeClaimTemplates:
  - metadata:
      name: mysql-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi  # Adjust storage size as needed
